apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: securityhub
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: gcr.io/mateo-burillo-ns/securityhub-frontend:latest
        ports:
        - containerPort: 3000
        env:
          - name: BASE_URL
            value: https://securityhub.dev
